# Sheldon configuration file
#
# See https://sheldon.cli.rs

shell = "zsh"

[templates]
defer = """{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}"""

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.promptinit]
inline = "autoload -U promptinit; promptinit"

[plugins.colored-man-pages]
github = "ael-code/zsh-colored-man-pages"

[plugins.mise]
inline = '''
zsh-defer -c 'eval "$($HOME/.local/bin/mise activate zsh)"'
'''

[plugins.bun]
inline = '[ -s "/home/levi/.bun/_bun" ] && source "/home/levi/.bun/_bun"'

# [plugins.rbenv]
# inline = 'eval "$(rbenv init - zsh)"'

[plugins.nodenv]
inline = '''
zsh-defer -c 'eval "$(nodenv init -)"'
'''

[plugins.deno]
inline = 'source "$HOME/.deno/env"'

# [plugins.asdf]
# local = "/usr/local/opt/asdf/libexec"
# use = ["asdf.sh"]
# apply = ["source"]

[plugins.pyenv]
inline = '''
zsh-defer -c 'eval "$(pyenv init -)"'
'''
# inline = 'eval "$(pyenv init -)"; eval "$(pyenv virtualenv-init -)"'

[plugins.sdkman]
inline = '''
zsh-defer -c '[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"'
'''

# update completions
[plugins.compinit]
inline = "compinit"

# Load local plugins last, so they can overwrite config
[plugins.dotfiles]
local = "~/.zsh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]
